files: ["**/*.js"] # No need to put app/assets/ or vendor/assets here
exclude_paths: ["**/lib"]
exclude_files: ["**/crypto_dep_bundle.js", "**/Web3.js"]
options:
  boss:       true
  browser:    true
  curly:      true
  eqeqeq:     true
  eqnull:     true
  expr:       true
  immed:      true
  indent:     2
  latedef:    true
  newcap:     true
  noarg:      true
  sub:        true
  trailing:   true
  undef:      true
  unused:     false
  globals:
    # external libs
    angular: true
    Moment: true
    moment: true
    google: true
    ga: true
    Showdown: true
    StripeCheckout: true

    # bad coding
    console: true
    confirm: true
    alert: true
    prompt: true
