attribute :id
attribute :priority
attribute :attempts
attribute :last_error
attribute :run_at
attribute :locked_at
attribute :failed_at
attribute :locked_by
attribute :created_at
attribute :updated_at