/*jshint -W117 */

'use strict';
// NEW APPROACH DO WORK OF END TO END TEST USING AS MUCH AS POSSIBLE
// WITHOUT SAVING STATE I.E. RELYING ON COOKIES OR API CALLS
// BASICALLY CHECK IF THROWS CORRECT ERRORS

